---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
language: ruby
notifications:
  email:
  - ehodel@fastly.com
rvm:
- 2.0
- 2.1
- 2.2
script: rake travis
